name: unittest
on:
  push:
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install
        run: |
          pnpm install
      - name: test
        run: |
          pnpm jest
